version: '3'
services:
  app:
    build:
      context: .
    restart: unless-stopped
    working_dir: /app
    volumes:
      - "${PWD:-./}:/app"
    ports:
      - "7000:80"

  db:
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: project
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
    driver: local
